Repo detailed UI
arthurshag/git-statistics pull request #13
Opened 2022-04-13 14:50 UTC by arthurshag

2022-04-15 12:36 UTC, jellymary requested changes
Замечания, которые не нашли своё место в отдельных комментах:

- [ ] Нет возможности попасть на repository-in-details (кроме как по прямой ссылке)
- [ ] Нет переходов от репозитория/ев к пользователю
- [ ] при переходе на `/repository/dan/player` на графиках "Last 100 Closed Pulls" и "Last 100 Closed Issues" появляется ошибка `Data column(s) for axis #0 cannot be of type string`. Причину не выяснила, но надо пофиксить

2022-04-15 12:36 UTC, jellymary commented on src/components/Repository/RepositoryParts/Commits&Events/CalendarChart.tsx
> +}
Можно тут прям написать `ReactGoogleChartProps['data']`. Ну а вообще это же компонент календаря, и мы знаем, что он принимает только даты и числа, поэтому можно уточнить это в типе пропс, да и разделить данные от легенды к графику
```suggestion
type Legend<T> = { type: T, id: string }
interface IProps {
    legend?: [Legend<'date'>, Legend<'number'>]
    dataChart?: Array<[Date, number]>
}
```
А потом уже в этом компоненте, а не в компонентах выше всё это добро склеивать

2022-04-15 12:36 UTC, jellymary commented on src/components/Repository/RepositoryParts/Issues&Pulls/ColumnChart.tsx
> +    dataChart: {} | any[] | undefined
Тут тоже замечание, как и к `CalendarChart`

2022-04-15 12:36 UTC, jellymary commented on src/components/Repository/RepositoryParts/Issues&Pulls/ColumnChart.tsx
> +            <span style={{color: "green"}}>Green</span>{" <24 hours "}</p>
Может легенду разделить по строчкам? А то сейчас её воспринимать не очень просто

2022-04-15 12:36 UTC, jellymary commented on src/components/Repository/RepositoryParts/Issues&Pulls/Issues.tsx
> +const getDataChart = (data: Endpoints["GET /repos/{owner}/{repo}/issues"]["response"]["data"]) => {
Вынести `Endpoints["GET /repos/{owner}/{repo}/issues"]["response"]["data"]` в тип / интерфейс

2022-04-15 12:36 UTC, jellymary commented on src/components/Repository/RepositoryParts/Issues&Pulls/Issues.tsx
> +        const dateDiff = Math.round((+new Date(c.closed_at) - +new Date(c.created_at)) / 1000 / 60 / 60);
Неявное преобразование к числу + непонятные константы (1000, 60 и 60). Непонятно в каких единицах измерения `dateDiff`

2022-04-15 12:36 UTC, jellymary commented on src/components/Repository/RepositoryParts/Issues&Pulls/Issues.tsx
> +    const dataChart: [string, string | number, object | string][] = [["Element", "Hours", {role: 'style'}]];
второй элемент – всегда `string`, зачем указывать `string | number`?
То же и с третим элементом

2022-04-15 12:36 UTC, jellymary commented on src/components/Repository/RepositoryParts/Issues&Pulls/Issues.tsx
> +    const dataChart: [string, string | number, object | string][] = [["Element", "Hours", {role: 'style'}]];
Легенде здесь не место, этот метод должен только подготавливать данные для графика

2022-04-15 12:36 UTC, jellymary commented on src/components/Repository/RepositoryParts/Issues&Pulls/Pulls.tsx
> +}
Практически полный дубль с функцией из соседнего файла, надо унифицировать, возможно унести в `ColumnDateChart`

2022-04-15 14:20 UTC, arthurshag commented on src/components/Repository/RepositoryParts/Owner/Owner.tsx
> +            <div className={classes.ownerType}>Type: {owner.type}</div>
Examples:
facebook/react type organization
reduxjs/redux type organization

2022-04-15 19:35 UTC, arthurshag commented on src/App.tsx
> +            <Header/>
Да, я для верстки вставил, нужно будет оформить navbar отдельно

2022-04-15 19:39 UTC, arthurshag commented on src/components/Repository/Repository.module.scss
> +.repository:first-child {
Аы, не помню как это я сделал, уберу

2022-04-15 19:42 UTC, arthurshag commented on src/components/Repository/Repository.tsx
> +                        <Owner owner={repository.owner}/>
Ля, это звучит -  сделаю.

2022-04-15 19:44 UTC, arthurshag commented on src/components/Repository/Repository.tsx
> +                        <Owner owner={repository.owner}/>
Надо подумать как разделять в плане ux/ui ссылки для пользователя. Я думаю, что взять иконку лого гитхаба и она будет ссылкой на гитхаб

2022-04-15 20:05 UTC, arthurshag commented on src/components/Repository/Repository.tsx
>                      </div>
??? 
Здесь ведь имеется в виду, что каждый пункт занимает свою строчку

2022-04-15 20:09 UTC, arthurshag commented on src/components/Repository/RepositoryParts/Owner/Owner.tsx
> +            <Title level={3}>Owner: <a href={owner.html_url}>{owner.login}</a></Title>
Сделал в этой ветки с репозиторием, другие ссылки в других ветках поменяю

2022-04-15 20:15 UTC, arthurshag commented on src/components/Repository/RepositoryParts/Languages.tsx
> +            <div>
Я так понимаю каждый блок должен быть отделён своим дивом

2022-04-16 08:03 UTC, arthurshag commented on src/components/Repository/Repository.tsx
> +                        <Owner owner={repository.owner}/>
На данный момент сделал так: имя - ссылка внутренняя по сайту, а иконка на гитхаб

2022-04-16 09:00 UTC, arthurshag commented on src/components/Repository/RepositoryParts/Issues&Pulls/Pulls.tsx
> +}
Да, точно, забыл

2022-04-20 12:56 UTC, jellymary commented on src/components/Repository/RepositoryParts/Owner/Owner.tsx
> +            <div className={classes.ownerType}>Type: {owner.type}</div>
Принимается

2022-04-20 13:04 UTC, jellymary commented on src/App.tsx
> +            <Header/>
Странно, ну ладно, не забудь)

2022-04-21 14:40 UTC, jellymary commented on src/components/Repository/RepositoryParts/Owner/Owner.tsx
> +                <Link to={`users/${owner.login}`}>{owner.login}</Link> {" "}
Не хватает `/` в ссылке перед `users`

2022-04-21 14:40 UTC, jellymary commented on src/components/Repository/Repository.tsx
>                      </div>
Что-то я затупила походу, когда смотрела первый раз. Всё ок)

2022-04-21 14:42 UTC, jellymary commented on src/components/Repository/RepositoryParts/Owner/Owner.tsx
> +            <Title level={3}>Owner: <a href={owner.html_url}>{owner.login}</a></Title>
Постарайся не забыть)

2022-04-21 14:44 UTC, jellymary commented on src/components/Repository/RepositoryParts/Languages.tsx
> +            <div>
Не обязательно, но желательно

2022-04-21 14:52 UTC, jellymary commented on src/components/Repository/RepositoryParts/Contributors/Contributors.tsx
> +                <Link to={`users/${c.login}`}>{c.login}</Link>{" "}
Тоже надо добавить `/`

2022-04-21 14:52 UTC, jellymary commented on src/components/Repository/RepositoryParts/Commits&Events/Events.tsx
Решение через `map` всё равно кажется мне более лаконичным, но и текущее норм

2022-04-21 14:59 UTC, jellymary commented on src/components/Repository/RepositoryParts/Contributors/Contributors.tsx
> +                <Link to={`users/${c.login}`}>{c.login}</Link>{" "}
Надо добавить `/` перед `users`, чтобы всё работало

2022-04-21 15:05 UTC, jellymary approved these changes

2022-04-22 08:10 UTC, merged